### ISSUE TITLE
sass_import requires nested task

### ISSUE THREAD

**Issue by lukewhyte** [eduardoboucas/grunt-sass-import#1]
The 'Basic Syntax' in the README includes the following code:

```
grunt.initConfig({
  sass_import: {
    options: {},
    files: {
      'main.scss': ['base/*', 'mixins/*', 'modules/*']
    },
  },
});
```

This will not create main.scss, as it appears grunt-sass-import, by default, attempts to run the nested task (eg. sass_import:files), which leads to the `this.files` in sass-import.js always being empty. I solved the problem by using the following structure:

```
grunt.initConfig({
  sass_import: {
    options: {},
    dist: {
      files: {
        'main.scss': ['base/*', 'mixins/*', 'modules/*']
      }
    }
  },
});
```

**Comment by eduardoboucas** [comment]
Thanks @lukewhyte! I'll amend the README.
