### ISSUE TITLE
jscs: All identifiers must be camelCase or UPPER_CASE

### ISSUE THREAD

**Issue by will-stone** [eduardoboucas/grunt-sass-import#8]
jscs does not like the non camelCase of "sass_import". I'm using this with the `yo angular` generator which by default runs jscs against the Gruntfile.js. May I suggest changing (or aliasing to avoid a breaking change) to `sassImport`?

**Comment by eduardoboucas** [comment]
Would you mind sending a PR?

**Comment by will-stone** [comment]
Done. It's pull request #9.
